### ISSUE TITLE
CortexJS demo does not always show a value for simplify

### ISSUE THREAD

**Issue by rs-mobitech** [cortex-js/compute-engine#102]
Am I correct in saying that the one example that does not show a value for simplify is because it's a floating point approximation? 

<img width="771" alt="Screenshot 2023-08-25 at 19 24 34" src="https://github.com/cortex-js/compute-engine/assets/39233783/3971e260-246a-4aa5-bcf5-b04a3df67a38">
<img width="762" alt="Screenshot 2023-08-25 at 19 21 30" src="https://github.com/cortex-js/compute-engine/assets/39233783/e78296a4-fe70-4438-8606-ff1dc9713bae">

If that is the case, then why is it than in my own code, which looks like this:

     let mfSLatex = parsedExpression.simplify().latex;

do I see that mfSLatex is populated with a value (with a missing parenthesis)

**Comment by arnog** [comment]
The output of `MathfieldElement.computeEngine.parse("\\sin\\left(1\\right)\\times\\frac52\\times\\cos\\left(1\\right)").simplify().latex` is `'\\frac{1}{2}(5\\sin(1)\\cos(1))'` and does not have a missing parenthesis.

In the case of the Compute Engine Demo page, it doesn't display the simplified version of the expression because it is structurally identical to the canonical form of the input expression.

**Comment by rs-mobitech** [comment]
Thanks for the explanation as to why the simplified version does not show.  I believe you can close this issue.

**Comment by arnog** [comment]
Closing, but note you can close issues you have opened.
