### ISSUE TITLE
Negative cubed roots should have a machine number result

### ISSUE THREAD

**Issue by manstie** [cortex-js/compute-engine#104]
E.g. (-20)^(1/3)

https://www.wolframalpha.com/input?i=%28-20%29%5E%281%2F3%29

![image](https://github.com/cortex-js/compute-engine/assets/12475567/eea80d5e-f513-4682-b4c0-aa2b0f5d87d0)

Auto / complex result is good, but there should also be a real number result

Expected: `-2.7144...`

Actual: `NaN`

![image](https://github.com/cortex-js/compute-engine/assets/12475567/673edcc4-8b87-4123-b299-ab19ec3e5ec3)

**Comment by arnog** [comment]
The `Root` function returns the principal value only. It is a function, not a relation. Otherwise, `["Root", 4, 2]` would have to return two values.

See discussions on this topic here: https://math.stackexchange.com/questions/2001412/why-do-we-assume-principal-root-for-the-notation-sqrt and https://math.stackexchange.com/questions/26363/square-roots-positive-and-negative

**Comment by manstie** [comment]
Is there another way to receive -2.7144 as the output?

**Comment by arnog** [comment]
I've added a `["ComplexRoots", -20, 3]` function that will return a list of the roots.
