### ISSUE TITLE
Compute Engine > Numeric evaluation

### ISSUE THREAD

**Issue by OleksiyPetroKovalenko** [cortex-js/compute-engine#109]
It appears there's an inconsistency since the first and last lines differ. Can you clarify which one is accurate? Also expr.N().numericValue.toNumber() gives me an error saying it's not a function.

<img width="785" alt="Screenshot 2023-09-05 at 21 38 40" src="https://github.com/cortex-js/compute-engine/assets/144126987/d37b5c4d-acb5-4154-95f0-2a2d2f974a5f">

**Comment by arnog** [comment]
> It appears there's an inconsistency since the first and last lines differ.
They differ because the input is different. The first is a numeric expression, the last is a symbolic expression. As the text above this screenshot explains:

> **To access a JavaScript machine number approximation of the result** use 
`valueOf()`. If `numericValue` is a machine number or a `Decimal` object, 
`valueOf()` will return a machine number approximation. Otherwise it returns
a string serialization of the MathJSON representation of the expression.

> Also expr.N().numericValue.toNumber() gives me an error saying it's not a function

It's impossible to say for sure without having access to the code you use, but that's probably because the value of `numericValue` is not a Decimal number. Did you try to look at that value?

**Comment by arnog** [comment]
`numericValue.toNumber()` only applies if the result is a `Decimal`. Again, I don't know what input you gave, so I can only speculate, but the result of your calculation appears to be a number, not a `Decimal`.

**Comment by arnog** [comment]
This is admittedly a bit tricky to do. In order to do this you would need access to the `Decimal` symbol representing the `Decimal` class. The tricky thing is that this symbol is not exported and if you imported the `decimal.js` library you would get a different instance with the same name, which would not work.

I'm going to add a `isBignum()` and `isComplex()` methods to the `ComputeEngine` class, which should solve this.

**Comment by arnog** [comment]
yes, but `expr.isComplex` and `expr.isExtendedComplex` indicate if the **expression** is in the domain of the Complex numbers. It doesn't say anything about the value of `expr.numericValue`. Ok, well, that's not exactly right. If `expr.isComplex` is true it is _likely_ that `ce.isCompelx(expr.numericValue)` will be true as well, but not certain. For example, you could declare that `z` is a Complex number. `ce.box("z").isComplex` would be true, but `ce.numericValue` would be null, since it does not have a value.

**Comment by arnog** [comment]
Done in 0.12.6
