### ISSUE TITLE
Evaluation with bracked number in string format does not work

### ISSUE THREAD

**Issue by lpettenella** [cortex-js/compute-engine#188]
I will take this simple expression as an example: 

["Add", 2, ["3"]]

With that above the result will be: **Add(3(), 2)**

Instead of the expected **5**. 

The cases in which it will work are:

- ["Add", 2, [3]]
- ["Add", 2, "3"]
- ["Add", 2, 3]

It seems that whenever a number is inserted in a string format and placed inside square brackets it will not be considered as a number.

**Comment by arnog** [comment]
That is not a valid MathJSON expression.

In MathJSON, arrays are used to represent functions. So ["3"] would represent a function named "3" (which is not valid identifier), which is being called with no arguments. The JavaScript equivalent would be `3()`.

There is not need for delimiters in MathJSON expressions, since they represent a tree. However, if you do need to represent delimiters, you can use a Delimiter expression: `["Add", 2, ["Delimiter", 3]]`

**Comment by lpettenella** [comment]
Thanks for the reply, I understand what you mean, however in light of this I don't get why the expression `["Add", 2, [3]]` works without problems, shouldn't the `[3]` be considered a function too?

**Comment by arnog** [comment]
If you give invalid input, there is no guarantee as to what happens.

**Comment by arnog** [comment]
I've adde a check to throw an error when using `ce.box()`. I don't know if that's how you ran into the problem, though.

**Comment by lpettenella** [comment]
yes I used `ce.box()`
