### ISSUE TITLE
Correct parsing of chains of < and <=

### ISSUE THREAD

**Issue by stefnotch** [cortex-js/compute-engine#25]
Parsing a chain of comparison operators, such as `1 <= x < 10` is a quite natural thing for humans to do. However, how to best represent this doesn't seem quite as clear cut to me. Which of the `<=` and `<` signs comes first? Or should we somehow encode that they're at the same level? Or..?

For the record, this is what the compute-engine currently does. It's a bit inconsistent.

![image](https://user-images.githubusercontent.com/10220080/151520760-5a11c947-5c17-459b-981b-954cbe4dcd1f.png)

**Comment by arnog** [comment]
That's a great question...

One option would be to parse this as `['And', ['LessEqual', 1, 2], ['Less', 2, 3'], ['LessEqual', 3, 4]]`...

**Comment by stefnotch** [comment]
True, that would work. The only downside is that one ends up losing the information about the `2` being the *same* value in `['LessEqual', 1, 2], ['Less', 2, 3']`.

I did ask someone who works a lot more with compilers than I do:
![0 <= a < b <= 10](https://cdn.discordapp.com/attachments/936359386551566337/936554295422246952/unknown.png)

their response was the following
```
class BinaryOp : Node {
  lhs : Node
  rightHands : List<(Operator, Node)>
}
```
```
BinaryOp(Const(0), [(LessEq, Var("a")), (Less, Var("b")), (LessEq, Const(10))]) 
```
This isn't immediately applicable to MathJson, but I still wanted to mention it.

**Comment by arnog** [comment]
That could be `['Inequality', 0, ['LessEqual', a], ['Less', b], ['LessEqual', 10]]`. It could work, but it introduces a completely new function, so it's something that needs to be handled. And it also uses somewhat weird single-operand inequalities. But then what does `['Less', b]` mean on its own?

Another option, `['And', ['LessEqual', 0, a], ['Less', b], ['LessEqual', 10]]`. But it would make `And` non-commutative, so that's a non-starter...

**Comment by stefnotch** [comment]
> That could be `['Inequality', 0, ['LessEqual', a], ['Less', b], ['LessEqual', 10]]`. It could work, but it introduces a completely new function, so it's something that needs to be handled. And it also uses somewhat weird single-operand inequalities. But then what does `['Less', b]` mean on its own?
> 
> Another option, `['And', ['LessEqual', 0, a], ['Less', b], ['LessEqual', 10]]`. But it would make `And` non-commutative, so that's a non-starter...

The upper could be justified by taking a page out of functional programming and going "partial functions are fineeee". As in, `['LessEqual', a]` could literally be `<= a`. [1] It is most certainly odd for comparison operators.
With addition, multiplication and more it looks a bit less surprising in my opinion.
`['Sum', 0, ['Add', 7], ['Subtract', 5]]`


[1] Or it could be `a <=`, depending on the convention.

**Comment by stefnotch** [comment]
I realized that Mathematica has the same problem. So clearly, it would make sense to check what they're doing.

The following piece of code
```mathematica
SetAttributes[fullFormString, HoldAll];
fullFormString[expr_] := ToString[Unevaluated @ FullForm[expr]]
fullFormString[1<x<=k]
```
(Source: https://mathematica.stackexchange.com/a/152438 )

returns
```
Inequality[1, Less, x, LessEqual, k]
```

Which seems like a rather reasonable way of doing it in the compute engine. I guess functions would have to be wrapped in brackets or something, so that they can be distinguished from variables.
`["Inequality", 1, ["Less"], "x", ["LessEqual"], "k"]`

**Comment by arnog** [comment]
Yes, that could work as well.

BTW, `["Less"]` is a valid MathJSON expression: it's the partial application of the `Less` function to no arguments (`["Less", 0]`  is the partial application of the `Less` function)

**Comment by svitrol** [comment]
Hello, I found some inconsistencies in basic usage:
![obrazek](https://github.com/cortex-js/compute-engine/assets/57999718/4929748f-ce98-4a53-9861-b6b2cab20089)
![obrazek](https://github.com/cortex-js/compute-engine/assets/57999718/37d0d0b8-6ffe-4825-ac31-1504d274740c)
So far okay, great work.
Here it starts to get weird.
![obrazek](https://github.com/cortex-js/compute-engine/assets/57999718/cfbcc512-ae41-4b2c-821a-b5f65cef63f8)
Latex formula shows some problem, but parsing still works.
![obrazek](https://github.com/cortex-js/compute-engine/assets/57999718/c8ad9bb7-6e33-4d74-9101-7c2ad287d820)
And here it does not parse at all.
To be complete:
![obrazek](https://github.com/cortex-js/compute-engine/assets/57999718/9200a981-5d3e-4b42-9460-befee1086d7d)
![obrazek](https://github.com/cortex-js/compute-engine/assets/57999718/d79a3e57-bdda-4b76-848c-1ebcddd4fc96)
Another strange behaviour is here:
![obrazek](https://github.com/cortex-js/compute-engine/assets/57999718/0ae2515d-1b81-4fb2-9da0-38e4bd6fef53)
["LessEqual", ["LessEqual", 0, "b"], 3]
 ["LessEqual", 0, "b"] result of this should be boolean value so am I comparing True <= 3?

**Comment by svitrol** [comment]
Right so I started from a place I got 'unexpected-argument'
https://github.com/cortex-js/compute-engine/blob/aa49d8b0099b2c47e4bd0a0d5dcaa75e74f40f6e/src/compute-engine/boxed-expression/validate.ts#L362

And I get here because here:
https://github.com/cortex-js/compute-engine/blob/aa49d8b0099b2c47e4bd0a0d5dcaa75e74f40f6e/src/compute-engine/boxed-expression/boxed-function.ts#L764
signature of the function does not have defined canonical.

So I went here where I can see that from the main comparison operators this one is the only one that does not have set 'canonical'.

https://github.com/cortex-js/compute-engine/blob/aa49d8b0099b2c47e4bd0a0d5dcaa75e74f40f6e/src/compute-engine/library/relational-operator.ts#L125

Like for example here canonical is
https://github.com/cortex-js/compute-engine/blob/aa49d8b0099b2c47e4bd0a0d5dcaa75e74f40f6e/src/compute-engine/library/relational-operator.ts#L153

So I guess fix would be to use canonical from GreaterEqual just not use reverse on args
      canonical: (ce, args) => ce._fn('LessEqual', args),

@arnog 
Hope it helps.

**Comment by arnog** [comment]
You're correct, there was a missing `canonical` handler. It has now been added. I have also fixed it so that chained relational operators get decomposed into boolean expressions, and so that they correctly compile to JavaScript.
