### ISSUE TITLE
throws error for \ce{\bond{~}}

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [cortex-js/compute-engine#56]
Throws error when trying to display partial bond.

<img width="1330" alt="image" src="https://user-images.githubusercontent.com/54144759/194260493-274d75b2-0997-44b7-a370-1c17b3458c13.png">

**Comment by arnog** [comment]
Good catch. I suggest filing the issue again the mhchem parser: https://github.com/mhchem/mhchemParser

**Comment by GaganpreetKaurKalsi** [comment]
I should file issue here or on mhchem repo? 
Could you elaborate a bit on the next steps?

**Comment by arnog** [comment]
Hi @GaganpreetKaurKalsi. The issue is not with cortex. As the console message indicate, this is an issue with the mhchem parser that doesn't handle a chemical equation made up of only one `\bond{-}` command. That's not a valid equation anyway, but since the author of mhchem is requesting to file an issue, I suggest you go to the mhchem parser repo and file and issue there.

**Comment by GaganpreetKaurKalsi** [comment]
> Hi @GaganpreetKaurKalsi. The issue is not with cortex. As the console message indicate, this is an issue with the mhchem parser that doesn't handle a chemical equation made up of only one `\bond{-}` command. That's not a valid equation anyway, but since the author of mhchem is requesting to file an issue, I suggest you go to the mhchem parser repo and file and issue there.

Okay! Thanks for your reponse.
