### ISSUE TITLE
Non-canonical form does not consistently parse fractions (Rational vs. Divide)

### ISSUE THREAD

**Issue by MatousAc** [cortex-js/compute-engine#65]
Either I don't understand how this is supposed to work, or there is a bug here. Canonical form is explained in the [documentation](https://cortexjs.io/compute-engine/guides/canonical-form/). The example shown is:
~~~
ce.parse("\\frac{3}{-5}")
// ➔ ["Rational", -3, 5]

ce.parse("\\frac{3}{-5}", {canonical: false})
// ➔ ["Divide", 3, -5]
~~~
However, it doesn't really seem like setting `canonical` to `false` really does anything. Rather, it seems that fractions with positive numerators and denominators are parsed as `Rational` while putting anything else in the numerator and denominator (including simply adding a `-`) will result in a `Divide`.

Example in this [CodePen](https://codepen.io/MatousAc/pen/JjZyBBX):
![mathLiveIssueDemo4](https://user-images.githubusercontent.com/56884762/202069994-14a68638-0eeb-4cfe-b4e1-4b49e3878520.gif)

Sod the question is two-fold:
1. Does setting `{canonical:false}` do anything in this context? I can't seem to get it to work.
2. Aren't fractions supposed to be interpreted as `Divide` rather than `Rational` in the non-canonical parsing mode?

Thanks @arnog!

**Comment by arnog** [comment]
It's much easier to respond to a bug report if you can provide some code I can copy and paste to debug it, rather than having to watch a screen recording and trying to figure out what the problem is about.

> 1. Does setting `{canonical:false}` do anything in this context? I can't seem to get it to work.
Yes,  it does. 

Compare:
```js
console.log(ce.parse('\\frac{3}{-4}', { canonical: false }).toJSON());
// -> ["Rational", 3, 4]
console.log(ce.parse('\\frac{3}{-4}', { canonical: true }).toJSON());
// ["Divide", 3, -4]
```
> 2. Aren't fractions supposed to be interpreted as Divide rather than Rational in the non-canonical parsing mode?

When `canonical` if false, if the `\frac` is a canonical rational (positive integer numerator, integer denominator), it is interpreted as a `Rational`, but if it is not,  it is interpreted as a `Divide`. In other words, the arguments are not modified when `canonical` is false.

**Comment by MatousAc** [comment]
I linked the Code Pen. I tried to make a minimal demonstration of the problem in there. The screen gif is just to demonstrate what I'm inputting to see the problem.

**Comment by MatousAc** [comment]
I see. I suppose I misunderstood what canonical rational meant.

**Comment by arnog** [comment]
The CodePen could be more useful if it demonstrated what the problem you are talking about is. It's a fairly generic code that doesn't demonstrate specifically the problem (I still have to know what I'm supposed to type in the field in order to see what the problem is), and it includes a lot of things that are not necessary to demonstrate the issue (some CSS, some UI, some event handling).

Since you ask, here's what would have made it easier:

> When executing: 
> ```js
> console.log(ce.parse('\\frac{3}{4}', { canonical: false }).toJSON());
> ```
> I get `["Rational", 3, 4]`.
> I was expecting `["Divide", 3, 4]` instead since `canonical` is `false`.

This is code that I can copy and paste to verify I get the same result, and I can clearly see what you are getting vs what you are expecting.

---

That said, to answer you question, if you want to avoid `Rational` in the json output, you can use this:
```js
ce.jsonSerializationOptions = { exclude: ['Rational'] };
console.log(ce.parse('\\frac{3}{4}', { canonical: false }).toJSON());
// -> ["Divide", 3, 4]
```
The `exclude` JSON serialization option can be used to indicate identifiers that should be avoided and replaced by an equivalent form when possible. In this case, `Rational` will be replaced with a `Divide`.

**Comment by MatousAc** [comment]
Thanks. Yeah, I think I understand that better now. I'm kinda new to issues (all of mine so far have been interactions with you) so thanks for your patience.
<hr/>
I tried your suggestion and that worked. Thank you so much!
